<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="DESKTOP-25I7L6M" name="com.testng.AttributeAnnotation" tests="8" failures="0" timestamp="2021-07-24T16:24:25 IST" time="2.120" errors="1">
  <testcase name="test1" time="0.046" classname="com.testng.AttributeAnnotation"/>
  <system-out/>
  <testcase name="test3" time="0.006" classname="com.testng.AttributeAnnotation"/>
  <system-out/>
  <testcase name="test5" time="0.008" classname="com.testng.AttributeAnnotation">
    <skipped/>
  </testcase> <!-- test5 -->
  <system-out/>
  <testcase name="test2" time="0.010" classname="com.testng.AttributeAnnotation"/>
  <system-out/>
  <testcase name="test8" time="0.008" classname="com.testng.AttributeAnnotation"/>
  <system-out/>
  <testcase name="test4" time="2.036" classname="com.testng.AttributeAnnotation">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.testng.AttributeAnnotation.test4() didn&#039;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.testng.AttributeAnnotation.test4() didn't finish within the time-out 2000
at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:371)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:282)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:605)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- test4 -->
  <system-out/>
  <testcase name="test7" time="0.006" classname="com.testng.AttributeAnnotation"/>
  <system-out/>
  <testcase name="test6" classname="com.testng.AttributeAnnotation">
    <skipped/>
  </testcase> <!-- test6 -->
  <system-out/>
</testsuite> <!-- com.testng.AttributeAnnotation -->
